### ISSUE TITLE
华为云安装 TASK [php-fpm : Install PHP70] 告警

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-lnmp#2]
[DEPRECATION WARNING]: Invoking "yum" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: {{ item }}`, please use `name: [u'php-fpm', u'php-pecl-
imagick', u'php-mysql', u'php-common', u'php-gd', u'php-mbstring', u'php-
mcrypt', u'php-devel', u'php-xml', u'php-pdo', u'php-bcmath', u'php-pear', u
'php-opcache', u'php-ldap', u'php-odbc', u'php-xmlrpc', u'php-json', u'php-
mysqlnd', u'php-pdo', u'php-pdo_dblib', u'php-recode', u'php-snmp', u'php-
soap', u'php-pecl-zip', u'php-curl', u'php-imap', u'php-pear-Net-SMTP', u'php-
pear-Mail']` and remove the loop. This feature will be removed in version 2.11.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

**Comment by Mozlk** [comment]
OK
